#!/bin/bash
# Like `tmux select-pane`, but if Vim is running in the current pane it sends
# a `<C-h/j/k/l>` keystroke to Vim instead.
set -e

cmd="$(tmux display -p '#{pane_current_command}')"
cmd="$(basename "$cmd" | tr A-Z a-z)"

if [ "${cmd%m}" = "nvi" ] || [ "${cmd%m}" = "nvi" ]; then
  vim_cmd="M-$(echo "${2#-}" | tr 'lLDURvh' '\\hjkl./')"
  # forward the keystroke to Vim
  tmux send-keys $vim_cmd
else
  tmux "$@"
fi
